// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Veterinaria.Data;

#nullable disable

namespace Veterinaria.Migrations
{
    [DbContext(typeof(VeterinariaDbContext))]
    partial class VeterinariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veterinaria.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Veterinaria.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<List<string>>("AdjuntosUrls")
                        .HasColumnType("text[]");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaProximaCita")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdMascota")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdMascota");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Veterinaria.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMascota"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdCliente");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Veterinaria.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NameRol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NameRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NameRol = "Veterinario"
                        });
                });

            modelBuilder.Entity("Veterinaria.Models.Usuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            EmailUser = "enriquearana1402@gmail.com",
                            IdRol = 1,
                            NameUser = "Administrador",
                            PasswordUser = "AQAAAAIAAYagAAAAEMGr17R7Y/RniLPqGvxDVm+wu1HJ+zO+blOyf+W61SXe3PmjMGjKzfLBaOrksbPaSw=="
                        },
                        new
                        {
                            IdUser = 2,
                            EmailUser = "vetnarro@gmail.com",
                            IdRol = 2,
                            NameUser = "Enrique Narro",
                            PasswordUser = "AQAAAAIAAYagAAAAELq7CIaD5kLrTogQkheXcq6zVVGqO+Za/pV1tM2GyBXozcCOMNiwp6jtFGL+YMyqhw=="
                        });
                });

            modelBuilder.Entity("Veterinaria.Models.Vacuna", b =>
                {
                    b.Property<int>("IdVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacuna"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdVacuna");

                    b.ToTable("Vacunas");

                    b.HasData(
                        new
                        {
                            IdVacuna = 1,
                            Nombre = "Triple felina Rinotraqueitis Panleucopenia",
                            Tipo = "Nobivac"
                        },
                        new
                        {
                            IdVacuna = 2,
                            Nombre = "Puppy DP",
                            Tipo = "Biocan"
                        },
                        new
                        {
                            IdVacuna = 3,
                            Nombre = "Cuádruple DHPPI",
                            Tipo = "Nobivac"
                        },
                        new
                        {
                            IdVacuna = 4,
                            Nombre = "Quíntuple DAPPv+L4",
                            Tipo = "Nobivac"
                        },
                        new
                        {
                            IdVacuna = 5,
                            Nombre = "Rabia (Rabies)",
                            Tipo = "Nobivac"
                        },
                        new
                        {
                            IdVacuna = 6,
                            Nombre = "Sextuple PDHLPiR",
                            Tipo = "Biocan"
                        });
                });

            modelBuilder.Entity("Veterinaria.Models.VacunaAplicada", b =>
                {
                    b.Property<int>("IdVacunaAplicada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacunaAplicada"));

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaProximaDosis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdMascota")
                        .HasColumnType("integer");

                    b.Property<int>("IdVacuna")
                        .HasColumnType("integer");

                    b.HasKey("IdVacunaAplicada");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdVacuna");

                    b.ToTable("VacunasAplicadas");
                });

            modelBuilder.Entity("Veterinaria.Models.Consulta", b =>
                {
                    b.HasOne("Veterinaria.Models.Mascota", "Mascota")
                        .WithMany("Consultas")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Veterinaria.Models.Mascota", b =>
                {
                    b.HasOne("Veterinaria.Models.Cliente", "Cliente")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Veterinaria.Models.Usuario", b =>
                {
                    b.HasOne("Veterinaria.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Veterinaria.Models.VacunaAplicada", b =>
                {
                    b.HasOne("Veterinaria.Models.Mascota", "Mascota")
                        .WithMany("VacunasAplicadas")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veterinaria.Models.Vacuna", "Vacuna")
                        .WithMany("VacunasAplicadas")
                        .HasForeignKey("IdVacuna")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Vacuna");
                });

            modelBuilder.Entity("Veterinaria.Models.Cliente", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Veterinaria.Models.Mascota", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("VacunasAplicadas");
                });

            modelBuilder.Entity("Veterinaria.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Veterinaria.Models.Vacuna", b =>
                {
                    b.Navigation("VacunasAplicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
